version: '3.9'

services:
  soil-app:
    container_name: soil-prediction-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_ENABLE_HMR=true
      - WATCHPACK_POLLING=true
    volumes:
      - type: bind
        source: .
        target: /usr/src/app

      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  node_modules:
    driver: local
