version: '3.9'

services:
  soil-app:
    container_name: soil-prediction-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_ENABLE_HMR=true
    volumes:
      - .:/app
      - ./app/.vite
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:3000']
      interval: 30s
      timeout: 10s
      retries: 3
